platform :ios, "5.0"
workspace 'OLCategoryHelperDemo'

# OLCategoryHelper
# pod 'OLCategoryHelper/UIImage+H568', :podspec => 'https://gist.github.com/payliu/6432443/raw/OLCategoryHelper.podspec'
# pod 'OLCategoryHelper/UIView+ViewFrameGeometry', :podspec => 'https://gist.github.com/payliu/6432443/raw/OLCategoryHelper.podspec'
# pod 'OLCategoryHelper/UINavigationController+Pilot', :podspec => 'https://gist.github.com/payliu/6432443/raw/OLCategoryHelper.podspec'
# 
pod 'OLCategoryHelper/Category/NSNumber', :podspec => 'https://gist.github.com/payliu/6432443/raw/OLCategoryHelper.podspec'
